#  Matrices


## Creating a numpy array

## Creating a row vector

In [1]:
import numpy as np
row = np.array([1,2,3])
print(row)



[1 2 3]


## Creating a col vector

In [2]:
print("\n")
col = np.array([[1],[2],[3]])
print(col)



[[1]
 [2]
 [3]]


## Creating a numpy matrix

In [3]:
matrix = np.matrix([[0,0,3],[0,0,6]])
print(matrix)

[[0 0 3]
 [0 0 6]]


###  Note :the matrix data structure is not recommended for two reasons. First, arrays are the de facto standard data structure of NumPy. Second, the vast majority of NumPy operations return arrays, not matrix objects

## Creating a sparce matrix

#### A frequent situation in machine learning is having a huge amount of data; however, most of the elements in the data are zeros. For example, imagine a matrix where the columns are every movie on Netflix, the rows are every Netflix user, and the values are how many times a user has watched that particular movie. This matrix would have tens of thousands of columns and millions of rows! However, since most users do not watch most movies, the vast majority of elements would be zero.vSparse matrices only store nonzero elements and assume all other values will be zero,vleading to significant computational savings. In our solution, we created a NumPyvarray with two nonzero values, then converted it into a sparse matrix. If we view the sparse matrix we can see that only the nonzero values are stored.

In [4]:
from scipy import sparse
ms = sparse.csr_matrix(matrix)
print(ms)


  (0, 2)	3
  (1, 2)	6


### https://docs.scipy.org/doc/scipy/reference/sparse.html

In [5]:
a1 = np.array([[1,0,0,0,0,90,0,0],[0,0,0,3,0,0,0,0],[58,5,5,0,0,0,0,0]])
s = sparse.csr_matrix(a1)
print(s)

  (0, 0)	1
  (0, 5)	90
  (1, 3)	3
  (2, 0)	58
  (2, 1)	5
  (2, 2)	5


## Selecting elements from the matrix

In [6]:
g = np.array([[1,2,3],[2,3,3],[4,5,9]])
print(g)
print("\n")

g[2,1]

#a = g[2,1]
#print(a)

[[1 2 3]
 [2 3 3]
 [4 5 9]]




5

### Note: Array/Matrix indexing starts from 0
### An entire row can be selected but a column cannot

## Vector selection

### vector_name[:]   selects all elements

In [7]:
k = np.array([9,6,5,7,4,5,3,2])
k[:]

array([9, 6, 5, 7, 4, 5, 3, 2])

In [8]:
k[:4]

array([9, 6, 5, 7])

In [9]:
k[4:]

array([4, 5, 3, 2])

In [10]:
k[1]

6

In [11]:
k[2]

5

In [12]:
k[-1]  ##Acesses the last element

2

#### g is a matrix

In [13]:
g[:3,:1]  ##here indexing starts from 1

array([[1],
       [2],
       [4]])

## Matrix operations

In [14]:
p = np.array([[5,4,3,2],[9,6,5,8]])
print(p)

[[5 4 3 2]
 [9 6 5 8]]


In [15]:
p.shape

(2, 4)

### matrix.size   gives total no of elements. ie rows * columns

In [16]:
p.size

8

### matrix.ndim   gives the dimention of the matrix

In [17]:
p.ndim

2

## Operation on Matrix elements

### applying function to various elements of a matrix

In [18]:
a = np.array([[5,4,6],[4,3,8]])
print(a)

[[5 4 6]
 [4 3 8]]


In [19]:
def count(l2):
    if l2 > 5:
        return 1
    else :
        return 0

In [20]:
vfunc = np.vectorize(count)
vfunc(a)

array([[0, 0, 1],
       [0, 0, 1]])

### np.vectorize(function) is used to enable a function to be used on each element of the matrix/vector

#### NumPy’s vectorize class converts a function into a function that can apply to all elements in an array or slice of an array. It’s worth noting that vectorize is essentially a for loop over the elements and does not increase performance. Furthermore, NumPy arrays allow us to perform operations between arrays even if their dimensions are not the same (a process called broadcasting)

In [21]:
a+ 20      ## this is broadcasting. 20 is converted into a vector of (2,3) and then added to array a

array([[25, 24, 26],
       [24, 23, 28]])

### np.max(array/matrix) and np.min(array/matrix) are used to find maximum and minimum element of a array/matrix

In [22]:
print(a)

[[5 4 6]
 [4 3 8]]


In [23]:
np.max(a+20)

28

In [24]:
np.min(a+1) 

4

### Often we want to know the maximum and minimum value in an array or subset of an array. axis = 0 compares columns and axis = 1 compares rows to give the max and min from the respective

In [25]:
np.max(a, axis=0)

array([5, 4, 8])

In [26]:
np.max(a, axis=1)

array([6, 8])

In [27]:
np.min(a, axis=0)

array([4, 3, 6])

In [28]:
np.min(a, axis=1)

array([4, 3])

### Finding mean, variance and standard deviation of a matrix a

In [29]:
np.mean(a)

5.0

In [30]:
np.var(a)

2.6666666666666665

In [31]:
np.std(a)

1.632993161855452

### Similarly if you want to find mean, variance and standard deviation for each row/col

In [32]:
np.mean(a, axis = 1)

array([5., 5.])

In [33]:
np.mean(a, axis = 0)

array([4.5, 3.5, 7. ])

In [34]:
np.var(a, axis = 1)

array([0.66666667, 4.66666667])

In [35]:
np.var(a, axis = 0)

array([0.25, 0.25, 1.  ])

In [36]:
np.std(a, axis = 1)

array([0.81649658, 2.1602469 ])

In [37]:
np.std(a, axis = 0)

array([0.5, 0.5, 1. ])

## Reshaping arrays

###  changing the shape (number of rows and columns) of an array without changing the element values.

In [38]:
print(a)

[[5 4 6]
 [4 3 8]]


In [39]:
a.reshape(3,2)

array([[5, 4],
       [6, 4],
       [3, 8]])

### While reshaping note that the product of order of original and new shape must remain the same ie(shape of the original and new matrix contain the same number of elements / the same size"

### One useful argument in reshape is -1, which effectively means “as many as needed,”so reshape(-1, 2) means two in a  row and as many columns as needed

In [40]:
a.reshape(-1,2)

array([[5, 4],
       [6, 4],
       [3, 8]])

In [41]:
a.reshape(-1,3)

array([[5, 4, 6],
       [4, 3, 8]])

In [42]:
a.reshape(2,-1)

array([[5, 4, 6],
       [4, 3, 8]])

In [43]:
a.reshape(6) #converts matrix to attay

array([5, 4, 6, 4, 3, 8])

## Transposing a matrix implies interchangig its rows and columns

In [44]:
print(a)

[[5 4 6]
 [4 3 8]]


In [45]:
a.T

array([[5, 4],
       [4, 3],
       [6, 8]])

In [46]:
arr = np.array([[1,2,3,4,5,6]]) 

In [47]:
print(arr)

[[1 2 3 4 5 6]]


In [48]:
arr.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## Flattning a matrix - Converting matrix of higher dimentions to 1D array

In [49]:
a.flatten()

array([5, 4, 6, 4, 3, 8])

### or

In [50]:
a.reshape(1,-1)

array([[5, 4, 6, 4, 3, 8]])

## Finding Rank of a matrix: 

In [51]:
np.linalg.matrix_rank(a)

2

## Finding determinant of a matrix

In [52]:
d = np.array([[1,2],[3,4]])

In [53]:
print(d)

[[1 2]
 [3 4]]


In [54]:
np.linalg.det(d)

-2.0000000000000004

### note: to perform the above operarion the matrix must be square. ie. no of rows is equal to no of columns

## To get diagonal elements of the matrix


In [55]:
print(d)

[[1 2]
 [3 4]]


In [56]:
d.diagonal()

array([1, 4])

### note: to perform the above operarion the matrix must be square. ie. no of rows is equal to no of columns

### NumPy makes getting the diagonal elements of a matrix easy with diagonal. It is also \possible to get a diagonal off from the main diagonal by using the offset parameter

In [57]:
po = np.array([[1,2,3],[2,5,3],[4,5,3]])
print(po)

[[1 2 3]
 [2 5 3]
 [4 5 3]]


In [58]:
po.diagonal(offset=1)

array([2, 3])

In [59]:
po.diagonal(offset=2)

array([3])

In [60]:
po.diagonal(offset=-1)

array([2, 5])

In [61]:
po.diagonal(offset=-2)

array([4])

In [62]:
po.diagonal(offset=0)

array([1, 5, 3])

## Trace of matrix - sum of the diagonal elements of the matrix

In [63]:
po.trace()

9

### or


In [64]:
print((sum(po.diagonal())))

9


## Eigenvaluesand eigen vectors

In [65]:
print(po)

[[1 2 3]
 [2 5 3]
 [4 5 3]]


In [66]:
eigenvalues, eigenvectors = np.linalg.eig(po)

In [67]:
print(eigenvalues)

[ 9.63634817 -1.72144251  1.08509434]


In [68]:
print(eigenvectors)

[[-0.38219408 -0.69988971  0.60251989]
 [-0.61255818 -0.10694405 -0.6560693 ]
 [-0.69188161  0.70619924  0.45446987]]


## Dot product

In [69]:
vectora = np.array([1,2,3])
vectorb = np.array([1,2,3])

In [70]:
print(vectora)

[1 2 3]


In [71]:
np.dot(vectora, vectorb)

14

## Addition and Subtraction

In [72]:
np.add(vectora, vectorb)

array([2, 4, 6])

In [73]:
np.subtract(vectora, vectorb)

array([0, 0, 0])

In [74]:
vectora + vectorb

array([2, 4, 6])

In [75]:
vectora - vectorb

array([0, 0, 0])

## Multiplication

In [76]:
mul1 = ([[2,3],[2,3]])

In [77]:
mul2 = ([[3,4],[6,7]])

In [78]:
print(mul1)

[[2, 3], [2, 3]]


In [79]:
np.dot(mul1,mul2)

array([[24, 29],
       [24, 29]])

In [80]:
print(mul2)

[[3, 4], [6, 7]]


## Elementwise multiplication

## Inverting a matrix

In [81]:
print(po)

[[1 2 3]
 [2 5 3]
 [4 5 3]]


In [82]:
np.linalg.inv(po)

array([[ 2.77555756e-17, -5.00000000e-01,  5.00000000e-01],
       [-3.33333333e-01,  5.00000000e-01, -1.66666667e-01],
       [ 5.55555556e-01, -1.66666667e-01, -5.55555556e-02]])

In [83]:
po @ np.linalg.inv(po)

array([[ 1.00000000e+00,  2.77555756e-17, -4.85722573e-17],
       [-2.22044605e-16,  1.00000000e+00, -1.59594560e-16],
       [-2.22044605e-16,  2.77555756e-17,  1.00000000e+00]])

## Generating random values

In [84]:
np.random.seed(0)

In [85]:
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

### np.random.randint(lowerlimit, upperlimit, how manyintegerss)

In [86]:
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [87]:
z = np.random.normal(0.0, 1.0, 3)
print(z)##mean 0 , std dev = 1

[-1.42232584  1.52006949 -0.29139398]


In [88]:
np.mean(z)

-0.06455010976050178

In [89]:
np.std(z)

1.2118900334160085

In [90]:
np.random.logistic(0.0, 1.0, 3) ##three numbers from a logistic distribution with mean 0.0 and scale of 1.0

array([-0.98118713, -0.08939902,  1.46416405])

In [91]:
np.random.uniform(1.0, 2.0, 3)##three numbers greater than or equal to 1.0 and less than 2.0

array([1.47997717, 1.3927848 , 1.83607876])